const response = {
  status: 0,
  offset: 0,
  total: 19,
  data: [
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: null,
      version: 0,
      sequence: 0,
      plannedStartDate: null,
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'aaaa',
      plannedDuration: '0.00',
      id: 18,
      user: { name: 'Administrator', id: 1, $version: 32 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '100.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: { name: 'Project 1', id: 1, $version: 0 },
      version: 10,
      sequence: 0,
      plannedStartDate: '2019-11-02T18:30Z',
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'Analysis',
      plannedDuration: '130.00',
      id: 1,
      user: { name: 'Administrator', id: 1, $version: 32 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: null,
      version: 3,
      sequence: 0,
      plannedStartDate: null,
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'Contact customer',
      plannedDuration: '0.00',
      id: 27,
      user: { name: 'Administrator', id: 1, $version: 32 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '2.79',
      parentTask: null,
      startToStartTaskSet: [],
      project: { name: 'Project 1', id: 1, $version: 0 },
      version: 29,
      sequence: 0,
      plannedStartDate: '2019-11-01T18:30Z',
      startToFinishTaskSet: [{ name: 'Implementation', id: 5, $version: 23 }],
      finishToStartTaskSet: [],
      name: 'Definition',
      plannedDuration: '497.00',
      id: 7,
      user: { name: 'Administrator', id: 1, $version: 32 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: { name: 'Project 2', id: 2, $version: 2 },
      version: 25,
      sequence: 0,
      plannedStartDate: '2019-11-04T18:30Z',
      startToFinishTaskSet: [],
      finishToStartTaskSet: [{ name: 'Definition', id: 7, $version: 29 }],
      name: 'Design',
      plannedDuration: '480.00',
      id: 8,
      user: { name: 'Demo User', id: 2, $version: 2 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: { name: 'Project 2', id: 2, $version: 2 },
      version: 11,
      sequence: 0,
      plannedStartDate: '2019-11-07T18:30Z',
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'Development',
      plannedDuration: '300.00',
      id: 9,
      user: { name: 'Demo User', id: 2, $version: 2 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: { name: 'Project 2', id: 2, $version: 2 },
      version: 1,
      sequence: 0,
      plannedStartDate: '2020-01-11T23:00Z',
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'Follow-up',
      plannedDuration: '600.00',
      id: 10,
      user: { name: 'Administrator', id: 1, $version: 32 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '11.64',
      parentTask: null,
      startToStartTaskSet: [],
      project: { name: 'Project 2', id: 2, $version: 2 },
      version: 23,
      sequence: 0,
      plannedStartDate: '2019-10-31T18:30Z',
      startToFinishTaskSet: [],
      finishToStartTaskSet: [{ name: 'Research', id: 6, $version: 24 }],
      name: 'Implementation',
      plannedDuration: '648.00',
      id: 5,
      user: { name: 'Demo User', id: 2, $version: 2 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: { name: 'Project 1', id: 1, $version: 0 },
      version: 1,
      sequence: 0,
      plannedStartDate: '2019-12-25T23:00Z',
      startToFinishTaskSet: [{ name: 'Follow-up', id: 10, $version: 1 }],
      finishToStartTaskSet: [],
      name: 'Presale analysis',
      plannedDuration: '240.00',
      id: 2,
      user: { name: 'Administrator', id: 1, $version: 32 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '61.45',
      parentTask: { name: 'Definition', id: 7, $version: 29 },
      startToStartTaskSet: [{ name: 'Definition', id: 7, $version: 29 }],
      project: { name: 'Project 2', id: 2, $version: 2 },
      version: 24,
      sequence: 0,
      plannedStartDate: '2019-11-05T18:30Z',
      startToFinishTaskSet: [{ name: 'Definition', id: 7, $version: 29 }],
      finishToStartTaskSet: [],
      name: 'Research',
      plannedDuration: '456.00',
      id: 6,
      user: { name: 'Administrator', id: 1, $version: 32 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: null,
      version: 2,
      sequence: 0,
      plannedStartDate: null,
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'sqdffqdsf',
      plannedDuration: '0.00',
      id: 20,
      user: { name: 'Demo User', id: 2, $version: 2 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [{ name: 'Follow-up', id: 10, $version: 1 }],
      project: { name: 'Project 1', id: 1, $version: 0 },
      version: 10,
      sequence: 0,
      plannedStartDate: '2019-11-30T18:30Z',
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'Test',
      plannedDuration: '1373.00',
      id: 4,
      user: { name: 'Demo User', id: 2, $version: 2 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: null,
      version: 0,
      sequence: 0,
      plannedStartDate: null,
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'Test',
      plannedDuration: '0.00',
      id: 11,
      user: { name: 'Administrator', id: 1, $version: 32 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: { name: 'Project 1', id: 1, $version: 0 },
      version: 0,
      sequence: 0,
      plannedStartDate: null,
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'Test',
      plannedDuration: '0.00',
      id: 22,
      user: { name: 'Demo User', id: 2, $version: 2 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: null,
      version: 2,
      sequence: 0,
      plannedStartDate: null,
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'Test',
      plannedDuration: '0.00',
      id: 24,
      user: { name: 'Administrator', id: 1, $version: 32 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: null,
      version: 7,
      sequence: 0,
      plannedStartDate: '2020-03-12T18:30Z',
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'Test',
      plannedDuration: '120.00',
      id: 26,
      user: { name: 'Administrator', id: 1, $version: 32 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: null,
      version: 1,
      sequence: 0,
      plannedStartDate: null,
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'test ioushqdfihjsqfdlhjqsd ijdbdfjnojqfdojqdsf mjnqsdkjf qmkjdfjsdf',
      plannedDuration: '0.00',
      id: 19,
      user: { name: 'Administrator', id: 1, $version: 32 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '50.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: null,
      version: 5,
      sequence: 0,
      plannedStartDate: '2020-05-17T18:30Z',
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'Training',
      plannedDuration: '672.00',
      id: 25,
      user: { name: 'Administrator', id: 1, $version: 32 },
    },
    {
      finishToFinishTaskSet: [],
      plannedProgress: '0.00',
      parentTask: null,
      startToStartTaskSet: [],
      project: { name: 'Project 2', id: 2, $version: 2 },
      version: 5,
      sequence: 0,
      plannedStartDate: '2020-01-11T23:00Z',
      startToFinishTaskSet: [],
      finishToStartTaskSet: [],
      name: 'UI Design',
      plannedDuration: '216.00',
      id: 3,
      user: { name: 'Demo User', id: 2, $version: 2 },
    },
  ]
    .filter(record => Number(record.plannedDuration) > 0)
    .map(record => {
      return {
        finishToFinish: record.finishToFinishTaskSet,
        progress: record.plannedProgress,
        parent: record.parentTask,
        startToStart: record.startToStartTaskSet,
        project: record.project,
        version: record.version,
        sequence: record.sequence,
        startDate: record.plannedStartDate,
        startToFinish: record.startToFinishTaskSet,
        finishToStart: record.finishToStartTaskSet,
        name: record.name,
        duration: record.plannedDuration,
        id: record.id,
        user: record.user,
      };
    }),
};

const { data } = response;

const modifyData = data
  .filter(item => !item.parent)
  .reduce(
    (list: any, item) => [
      ...list,
      item,
      ...data
        .filter($item => $item.parent?.id === item.id)
        .map($item => ({
          ...$item,
          startToStart: $item.startToStart.filter(task => task.id !== item.id),
        })),
    ],
    []
  );

const schema = {
  status: 0,
  data: {
    view: {
      viewId: 123,
      modelId: 53,
      name: 'project-task-gantt',
      title: 'Task Planning',
      model: 'com.axelor.project.db.ProjectTask',
      taskStart: 'plannedStartDate',
      taskDuration: 'plannedDuration',
      taskParent: 'parentTask',
      taskSequence: 'sequence',
      taskProgress: 'plannedProgress',
      startToStart: 'startToStartTaskSet',
      startToFinish: 'startToFinishTaskSet',
      finishToStart: 'finishToStartTaskSet',
      finishToFinish: 'finishToFinishTaskSet',
      items: [
        { type: 'field', name: 'name', autoTitle: 'Name' },
        { type: 'field', name: 'project', autoTitle: 'Project' },
        { type: 'field', name: 'user', autoTitle: 'User' },
      ],
      type: 'gantt',
    },
    perms: null,
    fields: [
      { name: 'name', type: 'STRING', title: 'Task Summary', required: true },
      {
        targetName: 'name',
        targetSearch: ['name'],
        name: 'project',
        perms: null,
        type: 'MANY_TO_ONE',
        title: 'Project',
        target: 'com.axelor.project.db.Project',
      },
      {
        targetName: 'name',
        targetSearch: ['name', 'code'],
        name: 'user',
        perms: null,
        type: 'MANY_TO_ONE',
        title: 'User',
        required: true,
        target: 'com.axelor.auth.db.User',
      },
    ],
  },
};

const DATA = {
  ...response,
  items: schema.data.view.items.map(item => {
    const field = schema.data.fields.find(f => f.name === item.name);
    const attrs: any = {};
    if (field?.type === 'MANY_TO_ONE' && field.targetName) {
      attrs.formatter = (data: any, field: any) => {
        const value = data[field.name];
        return value && value[field.targetName];
      };
    }
    return { ...item, ...field, ...attrs };
  }),
  data: modifyData,
};

export default DATA;
